version: '3.8'

services:
  # 1. The Database (Postgres)
  postgres:
    image: postgres:15-alpine
    container_name: nexus_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: payment_gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Queue/Cache (Redis)
  redis:
    image: redis:7-alpine
    container_name: nexus_queue
    ports:
      - "6379:6379"

volumes:
  postgres_data: